#server:
#  port: 8080
#
#spring:
#  application:
#    name: demo-web
#  freemarker:
#    expose-request-attributes: true
#    expose-spring-macro-helpers: true
#    request-context-attribute: request
#    cache: false
#    settings:
#      auto_import: /spring.ftl as spring
#  resources:
#    chain:
#      enabled: true
#  redis:
#    host: 172.16.120.153
#    port: 30007
#  datasource:
#    url: jdbc:mariadb://172.16.120.153:30006/test?characterEncoding=utf-8
#    username: root
#    password: 123456
#    driver-class-name: org.mariadb.jdbc.Driver
#    initialSize: 10
#    maxActive: 20
#    minIdle: 1
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validation-query: select 1
#    test-while-idle: true
#
#
#mybatis:
#  config-location: classpath:mybatis-config.xml
#
#
#logging:
#  level:
#    root: info
#    com.szss: debug



server:
  port: 8080

spring:
  application:
    name: demo-web
  freemarker:
    expose-request-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
    cache: false
    settings:
      auto_import: /spring.ftl as spring
  resources:
    chain:
      enabled: true
  redis:
    host: ${MY_REDIS_HOST}
    port: ${MY_REDIS_PORT}
  datasource:
    url: ${MY_DATASOURCE_URL}
    username: ${MY_DATASOURCE_USERNAME}
    password: ${MY_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    initialSize: 10
    maxActive: 20
    minIdle: 1
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validation-query: select 1
    test-while-idle: true


mybatis:
  config-location: classpath:mybatis-config.xml


logging:
  level:
    root: info
    com.szss: debug


#server:
#  port: 8080
#
#spring:
#  application:
#    name: demo-web
#  freemarker:
#    expose-request-attributes: true
#    expose-spring-macro-helpers: true
#    request-context-attribute: request
#    cache: false
#    settings:
#      auto_import: /spring.ftl as spring
#  resources:
#    chain:
#      enabled: true
#  redis:
#    host: redis
#  datasource:
#    url: jdbc:mariadb://mysql:3306/test?characterEncoding=utf-8
#    username: root
#    password: 123456
#    driver-class-name: org.mariadb.jdbc.Driver
#    initialSize: 10
#    maxActive: 20
#    minIdle: 1
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validation-query: select 1
#    test-while-idle: true
#
#
#mybatis:
#  config-location: classpath:mybatis-config.xml
#
#
#logging:
#  level:
#    root: info

